# import Query from './types/snap.gql'
# import Mutation from './types/snap.gql'
# import Subscription from './types/snap.gql'


# import Query from './types/token.gql'


# import Query from './types/user.gql'
# import Mutation from './types/user.gql'
# import Subscription from './types/user.gql'