scalar Date

type Query {
  snap(id: ID!): Snap!
  snaps: [Snap!]!
}

type Snap {
  id: ID!
  user_id: ID!
  text: String!
  createdAt: Date!
  user: User!
}

type Mutation {
  createSnap(data: createSnapInput!): Snap
}

input createSnapInput {
  user_id: ID!
  text: String!
}

type Subscription {
  snap(user_id: ID): Snap!
}
